# config.yml

server:
  applicationConnectors:
    - type: http
      port: 8080  # Render expects apps to bind to this port
  adminConnectors:
    - type: http
      port: 8081  # Optional: admin interface (not exposed publicly)
  
logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    your.package.name: DEBUG  # Replace with your actual base package name

  appenders:
    - type: console
      threshold: INFO
      target: stdout
      logFormat: "%d{ISO8601} %-5p [%t] %c: %m%n"
